storage:
  url: http://localhost:8081
crypto:
  bootstrapidentity:
    name: seraphin
    executor:
      Asymmetric:
        Secret:
          SodiumOxide: {}
    source:
      Bytes:
        Fs:
          path: keys/private/admin.key
    alg: curve25519xsalsa20poly1305,
    encrypted_by: "noone"
