storage:
  url: http://localhost:8081
crypto:
  bootstrapidentity:
    Asymmetric:
      Secret:
        SodiumOxide:
          source:
            Bytes:
              Fs:
                path: keys/private/admin.key
          alg: curve25519xsalsa20poly1305,
          name: seraphin
  symmetric:
    defaultkeyname: default
